apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend-service-deployment
  labels:
    app: rfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rfs
  template:
    metadata:
      labels:
        app: rfs
    spec:
      containers:
        - name: rfs
          image: distributed07/react-frontend-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: react-frontend-service
spec:
  type: NodePort
  selector:
    app: rfs
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000