name: Build Docker Image CI - React Frontend

on:
  push:
    branches: [main]
    paths: [Frontend/ui/**]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.13.2"
      - name: Build node app
        working-directory: Frontend/ui
        run: | 
          npm install
          npm run build
        env:
          CI: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push react-frontend-service
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: distributed07/react-frontend-service_dev:latest
          platforms: linux/arm64,linux/amd64
          context: ./Frontend/ui
